### ISSUE TITLE
Heron/Rapier-style ShapeCasting

### ISSUE THREAD

**Issue by cvvv24** [meowitzher/bevy_sepax2d#3]
I'm looking into moving my bevy platformer game from heron to bevy_sepax2d, however from my current understanding sepax is currenly missing some convenient funcitonality.
What I'm looking for is a simple way to do a shapecast using an entity's collider, apply masks and groups, and if the collision is hit check the exact position where the collision happened.
I'm a beginner bevy/rust user so it's possible that sepax already allows all of this and I'm just not understanding how to do this in sepax.
Sorry if that's the case!
I know casting rays was added in the recent update but it seems to be something slightly different than what I'm looking for / missing some funcitonality?

Example of how I'm currently doing this in heron:
let hit = physics_world.shape_cast_with_filter(
                shape: collider,
                start_position: transform.translation,
                start_rotation: transform.rotation,
                ray: velocity_vector,
                layers: CollisionLayers::none()
                .with_group(ColliderTypes::Player)
                .with_mask(ColliderTypes::Wall),
                filter: |_enityty| true,
            );

**Comment by meowitzher** [comment]
Thanks for your input!

Currently sepax2d doesn't support any kind of casting - the ray functionality is only ray intersection. It doesn't calculate the point where the ray hits the shape: that is a more involved process.

My current thought process with Sepax2d (and its Bevy plugin) is to have it occupy a lower level than Heron and Rapier - simpler to get started with less functionality that handles the basics. My initial response is that, if I were you, I'd trust Heron more than sepax2d! It's been around longer and I'd consider it far more stable, and if you already have a solution that works with it, I think that'd be your best bet in the long run.

That said I'm not opposed to looking into adding this functionality if there's a strong desire for it or there's a specific reason why Heron's not an ideal solution. Just be warned it'll likely not be added as a feature for awhile in that case! (If others have suggestions or would like to try and add it themselves, they are totally welcome to!)
